#!/bin/bash -e

decorate() {
    echo
    echo $1
    python -c "print '=' * ${#1}"
}

decorate "Install homebrew"
which brew > /dev/null && echo ok || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
decorate "brew install ansible"
which ansible > /dev/null && echo ok || brew install ansible
decorate "brew install git"
which git > /dev/null && echo ok || brew install git
decorate "brew install golang"
which go > /dev/null && echo ok || brew install golang
export GOPATH=$HOME/repos
export PATH=$GOPATH/bin:$PATH
export GHQ_ROOT=$GOPATH/src
decorate "go get github.com/motemen/ghq"
go get github.com/motemen/ghq
decorate "ghq get suzuki-shunsuke/ansible-playbook-mac"
ghq get suzuki-shunsuke/ansible-playbook-mac
cd $GHQ_ROOT/github.com/suzuki-shunsuke/ansible-playbook-mac
decorate "ansible-galaxy install -r roles.yml"
ansible-galaxy install -r roles.yml
decorate "ansible-playbook -i localhost --ask-become-pass playbook.yml"
ansible-playbook -i localhost --ask-become-pass playbook.yml
